module DaycareView exposing (plannerViewGenerate, sidebarViewGenerate)

import Html exposing (..)
import Html.Attributes exposing (..)


sidebarViewGenerate : Model -> Html msg
sidebarViewGenerate model =
    [ [ div [ class "head" ]
            [ h2 [ class "sidebar-header" ]
                [ text "daycare" ]
            ]
      , div [ class "sidebar-frequent" ]
            [ h3 []
                [ text "frequent" ]
            , ul [ class "frequent-list" ]
                [ li []
                    [ text "test" ]
                , li []
                    [ text "test1" ]
                , li []
                    [ text "test2" ]
                , li []
                    [ text "test3tet" ]
                ]
            ]
      , div [ class "sidebar-lifegoals" ]
            [ h3 []
                [ text "lifegoals" ]
            , ul [ class "lifegoals-list" ]
                [ li [ class "lifegoal" ]
                    [ text "test1" ]
                , li [ class "lifegoal" ]
                    [ text "test2" ]
                , li [ class "lifegoal" ]
                    [ text "test23" ]
                , li [ class "lifegoal" ]
                    [ text "test3" ]
                ]
            ]
      ]
    ]


plannerViewGenerate model =
    [ div [ class "days" ]
        [ ul [ class "days-list" ]
            [ li [ class "day" ]
                [ div [ class "day-header" ]
                    [ h4 []
                        [ text "Monday, 13th of March 2015" ]
                    , div [ class "attributes" ]
                        [ ul [ class "attributes-list" ]
                            [ li [ class "attribute" ]
                                [ text "X" ]
                            , li [ class "attribute" ]
                                [ text "A" ]
                            ]
                        ]
                    , p [ class "day-description" ]
                        [ text "Day was very good" ]
                    ]
                ]
            ]
        ]
    ]
